## config file for pipewire if radar installed on stratux
## increases buffer size, otherwise buffer underrun errors occur on stratux with radar installed

context.properties = {
    default.clock.quantum = 1024
    default.clock.min-quantum = 1024
}
